In [31]:
print("Hello I'm Beryl excited to be here")

Hello I'm Beryl excited to be here


In [32]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.1+cu121


INTRODUCTION TO TENSORS

CREATING TENSORS

In [33]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [34]:
scalar.ndim

0

In [35]:
scalar.item()

7

In [36]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [37]:
vector.ndim

1

In [38]:
vector.shape

torch.Size([2])

In [39]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [40]:
MATRIX.ndim

2

In [41]:
MATRIX[1]

tensor([ 9, 10])

In [42]:
MATRIX.shape

torch.Size([2, 2])

In [43]:
# TENSOR
TENSOR =torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [44]:
TENSOR.ndim

3

In [45]:
TENSOR.shape

torch.Size([1, 3, 3])

In [46]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Random Tensors
why random Tensors?
Random Tensors
1 start with Random networks
look data
update random numbers
look a data update data
https://pytorch.org/docs/stable/generated/torch.rand.html

In [47]:
### Random Tensors
# create random Tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor


tensor([[0.2601, 0.7823, 0.5988, 0.7003],
        [0.4225, 0.7627, 0.8921, 0.6351],
        [0.7584, 0.0227, 0.2713, 0.7738]])

In [48]:
random_tensor.ndim

2

In [49]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

ZEROS AND ONES

In [50]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [51]:
# creata e tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [52]:
ones.dtype

torch.float32

CREATE A RANGE OF TENSORS AND TENSORS-LIKE

In [53]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Tensors like

In [54]:
# creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

TENSOR DATATYPES
tensor not write data type
tensor not right shape
tensor not on the right device

In [55]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,
                               device=None,)
float_32_tensor

tensor([3., 6., 9.])

In [56]:
float_32_tensor.dtype

torch.float32

In [57]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [58]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

GETTING INFO FROM A TENSOR
to get datatype Tensor_= tensor.dtype
 to get the shape = tensor.shape
 to get the right device = tensor.device

In [59]:
# Getting Information from tensors
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8561, 0.5779, 0.6532, 0.9702],
        [0.8632, 0.2207, 0.6349, 0.4313],
        [0.2737, 0.5804, 0.7521, 0.2880]])

In [60]:
# find out the details about some tensor
print(some_tensor)
print(some_tensor.shape)
print(some_tensor.device)
print(some_tensor.dtype)

tensor([[0.8561, 0.5779, 0.6532, 0.9702],
        [0.8632, 0.2207, 0.6349, 0.4313],
        [0.2737, 0.5804, 0.7521, 0.2880]])
torch.Size([3, 4])
cpu
torch.float32


print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}
print(f"Device of tensor: {some_tensor.device})

Manupulation
Tensor operation include
Add
sub
multiplication
division
matrix multiplication

In [61]:
####manipulatingtensors operations

In [62]:
# create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [63]:
tensor * 10

tensor([10, 20, 30])

In [64]:
tensor

tensor([1, 2, 3])

In [65]:
tensor - 10

tensor([-9, -8, -7])

In [66]:
tensor / 2

tensor([0.5000, 1.0000, 1.5000])

MATRIX MULTIPLICATION
two types of multiplication
-Normal one (element wise)
-Matrix multiplication
Two rules Matrix multiplication most satisfy
1.the innner dimensions most match.
(3, 2) @ (3, 2) -wont match
(2, 3) @ (3, 2) - will work
(3, 2) @ (2, 3)
2.the resulting matrix has the shape of the outer dimensions:

In [67]:
#element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [68]:
#matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [69]:
#matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [70]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)

tensor(1)
tensor(5)
tensor(14)
CPU times: user 4.62 ms, sys: 0 ns, total: 4.62 ms
Wall time: 6.65 ms


In [71]:
##one of the most cmmon error in deep learning is shape error

one of the most common error in deep learning.: shape errors
Matrix multipliation operations works when Tensor _B is transposed.

In [73]:
#shapes for matrix multiplication
import torch
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#trch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [74]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [75]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [76]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [77]:
#the matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


TENSOR AGGRERATION -Finding the min, max, mean, sum

In [78]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [79]:
#### find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [80]:
##find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [81]:
### find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

the torch.mean  function requires a tensor of float 32 datatype to work

In [82]:
### find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

FINDING THE POSITIONAL MIN AND MAX

In [83]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [84]:
#finding the positional tensor that has min and max value with armin() returns the index
x.argmin()

tensor(0)

In [85]:
x[0]

tensor(0)

In [86]:
x.argmax()

tensor(9)

In [87]:
x[9]

tensor(90)

RESHAPING STACKING SQUEEZING  UNSQUEEZING TENSORS
* Reshaping - reshapes an input tensor to a defined shapes
* view - return a view of an input of a certain shape but keep the same memory as the original one
* stacking - combining multiple tensor ontop of each other. torch.vstark, torch.hstark. Torch.stack
* squeeze -m removeall `1`dimensions from a tensor.
* unsqueeze _ add 1 dimension target tensor
* permute- return a view point  with the dimensions permuted (swapped in a certain nway

In [97]:
#create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [99]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [100]:
#change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

view shares the same memory as the original imput

In [101]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [102]:
#changes z changes x blc they both share the same memory
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [105]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

SQUEEZE AND UNSQUEEZE AND PERMUTATION

In [110]:
# torch.squeeze() - removes all single dimensions frm a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#remove extra dimension from x shaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [111]:
#torch.unsqueze() -nadd a single dimension to a target tensor at a specific dimension
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#add extra dimension from x
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [112]:
x_reshaped.shape

torch.Size([1, 9])

In [108]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [109]:
x_reshaped.squeeze().shape

torch.Size([9])

In [114]:
#torch,permute = rearranges the dimensions of a target tensor in the specific order
x_original = torch.rand(size=(224, 224, 3)) # height, width, colour channels

#permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # colour channels, height, width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


x_original shares the same memory as x_permuted

In [115]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

  INDEXING (selectiong data from tensors)
  indexing with pytorch is same as indexing in nympy

In [117]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [118]:
#lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [119]:
#lets index middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [120]:
#lets index on most inner bracket (last dim)
x[0][0][0]

tensor(1)

we can only index from the 0 dimension if the dimension is 1

In [121]:
#you can use ":" to select all of target dim
x[:, 0]

tensor([[1, 2, 3]])

In [122]:
#get all values of 0th and 1st dim but index 1 of 2 dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [123]:
#get all values of 0 dim but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [124]:
#get index of 0 of 0th and 1st dim and all values of the 2nd dim
x[0, 0, :]

tensor([1, 2, 3])

In [125]:
#index on x to return 9
print(x[0][2][2])

#index on x to return 3, 6,
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


In [126]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [127]:
1

1

PYTORCH TENSORS AND NUMPY
-Pytorch has funtionality to work with nympy
- data in numpy, want in pytorch tensor -> `torch.from_numpy(ndarray)
-pytorch tensor-> Nympy -> torch.Tensor.numpy()
numpy data type is float64/ pytorch is float32

In [128]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor
#warning when converting from nympy->pytorch, pytorch reflect nympy default datatype of float64 unless specified

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [129]:
tensor.dtype

torch.float64

In [130]:
#change the value of the array what will this do to the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [131]:
#changes from Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [132]:
numpy_tensor.dtype

dtype('float32')

In [134]:
#change tensor what happens to numpy tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

numby tensor remains the same blc it doesnt share memory

PYTORCH REPRODUCIBILITY
(trying to take random out of random)
How a Neural Network Learns:
- start with random numbers -> tensor operations ->updata random numbers to try and make them better representation of the data again-> again-> again
-to reduce the randomness in neural networks  and pytocrch comes the concept of random seed
essential what the random see does is "flavor' the randomness
more resources https://pytorch.org/docs/stable/notes/randomness.html


In [137]:
torch.rand(3, 3)

tensor([[0.4560, 0.9069, 0.8051],
        [0.5451, 0.3602, 0.2916],
        [0.9869, 0.1792, 0.0890]])

In [139]:
import torch
#create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6418, 0.9259, 0.1492, 0.9108],
        [0.4054, 0.7153, 0.4154, 0.9440],
        [0.5030, 0.6822, 0.6834, 0.5926]])
tensor([[0.6478, 0.4183, 0.3275, 0.0073],
        [0.1848, 0.0519, 0.0577, 0.7645],
        [0.2612, 0.7207, 0.9565, 0.1573]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [140]:
#lets make some random but reproducible tensors
import torch

#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


DIFERRENT WAYS OF ACCESING DIFFERENT GPU
#MAKING FASTER COMPUTATION
gETTING A GOOD GPU
*easiest- google colab/colab pro/colab pro+(options to upgrade)
*use your own gpu (https://bizon-tech.com/blog/best-gpu-for-data-science#:~:text=NVIDIA%20A100%3A%20Known%20for%20its,large%2Dscale%20data%20science%20tasks. )
3) USE CLOUD COMPUTING - GCP, AWS,AZURRE THESE SERVICES ALLOW YOU TO RENT COMPUTERS ON THE CLOUD AND ACCESS THEM
for 2, 3 use pytorch,org
https://pytorch.org/docs/stable/notes/cuda.html


In [1]:
#getting a GPU
!nvidia-smi


Wed Jul 31 07:25:27 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
##check for GPU access with PYTORCH
import torch
torch.cuda.is_available()

True

In [16]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
#counting the number of devices
torch.cuda.device_count()

1

PUTTING TENSORS AND MODELS ON THE GPU
THE reasons we want tensors?models on the GPU is because using a GPU results is faster computations

In [13]:
#create a tensor (default is on CPU)
tensor = torch.tensor([1, 2, 3])

#tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [17]:
### setup a diagnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

### moving tensor to gpuif available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

MOVING TENSORS BACK TO THE CPU

In [18]:
### IF tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()



TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [19]:
#to fix the GPU tensor with numpy issue. can we first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu


array([1, 2, 3])

In [20]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

EXERCISE AND CURRICULUMS
Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.
Create a random tensor with shape (7, 7).
Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
Set the random seed to 0 and do exercises 2 & 3 over again.
Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
Find the maximum and minimum values of the output of 7.
Find the maximum and minimum index values of the output of 7.
Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape

In [21]:
tensor = torch.rand(7, 7)
tensor

tensor([[0.6402, 0.8545, 0.2887, 0.2502, 0.4705, 0.2045, 0.6970],
        [0.5838, 0.3471, 0.5957, 0.7289, 0.9343, 0.9142, 0.1371],
        [0.4143, 0.0015, 0.7069, 0.7521, 0.3178, 0.9654, 0.1801],
        [0.6001, 0.0013, 0.9529, 0.1306, 0.9558, 0.5724, 0.8681],
        [0.8042, 0.0052, 0.2457, 0.5965, 0.9546, 0.1500, 0.2585],
        [0.6464, 0.5010, 0.7319, 0.9130, 0.7494, 0.3777, 0.9748],
        [0.3560, 0.6889, 0.0033, 0.1350, 0.4002, 0.0395, 0.6434]])

In [22]:
tensor.shape

torch.Size([7, 7])

In [26]:
#create a tensor and then multiply by 2
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)
tensor_A, tensor_B
torch.matmul(tensor_A, tensor_B.T)



tensor([[2.1753],
        [1.5316],
        [1.5773],
        [1.4634],
        [2.0557],
        [1.5625],
        [1.7736]])

In [27]:
#set random seed to 0
torch.manual_seed(0)
tensor_A = torch.rand(7, 7)
tensor_B = torch.rand(1, 7)
tensor_A, tensor_B
torch.matmul(tensor_A, tensor_B.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [28]:
#find GPU equivalent
import torch
torch.cuda.is_available()

True

In [31]:
#set random seed to 1234
torch.manual_seed(1234)
#create two random tensors on GPU
tensor_A = torch.rand(2, 3)
tensor_B = torch.rand(2, 3)
tensor_A, tensor_B
# send them to GPU
tensor_A = tensor_A.to(device)
tensor_B = tensor_B.to(device)
tensor_A, tensor_B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [33]:
#multiply matrix in 6
torch.matmul(tensor_A, tensor_B.T)
#access gpu
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C.shape

torch.Size([2, 2])

In [34]:
#find min value
torch.min(tensor_C)

tensor(0.3647, device='cuda:0')

In [35]:
#find max value
torch.max(tensor_C)

tensor(0.5617, device='cuda:0')

In [36]:
#find min index value
torch.argmin(tensor_C)

tensor(0, device='cuda:0')

In [37]:
#find the max index value
torch.argmax(tensor_C)

tensor(3, device='cuda:0')

In [38]:
#make a random tenshor shape
random_tensor = torch.arange(1, 10)
random_tensor, random_tensor.shape


(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [40]:
#set seed to 7 and print out the first tensor
torch.manual_seed(7)
random_tensor = torch.rand(1, 1, 1, 10)
random_tensor, random_tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

# New Section